# ============================================================================
# Outputs
# ============================================================================

output "region" {
  description = "AWS region"
  value       = var.region
}

# VPC
output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = aws_subnet.private[*].id
}

output "public_subnet_ids" {
  description = "Public subnet IDs"
  value       = aws_subnet.public[*].id
}

# EKS
output "cluster_name" {
  description = "EKS cluster name"
  value       = aws_eks_cluster.main.name
}

output "cluster_endpoint" {
  description = "EKS cluster API endpoint"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_certificate_authority" {
  description = "EKS cluster CA certificate"
  value       = aws_eks_cluster.main.certificate_authority[0].data
  sensitive   = true
}

output "cluster_security_group_id" {
  description = "EKS cluster security group ID"
  value       = aws_security_group.eks_cluster.id
}

# RDS
output "database_endpoint" {
  description = "RDS instance endpoint"
  value       = aws_db_instance.main.endpoint
}

output "database_name" {
  description = "Database name"
  value       = aws_db_instance.main.db_name
}

output "database_secret_arn" {
  description = "ARN of the Secrets Manager secret containing DB credentials"
  value       = aws_secretsmanager_secret.db_password.arn
}

# S3
output "backup_bucket" {
  description = "S3 bucket for backups"
  value       = aws_s3_bucket.backups.bucket
}

output "backup_bucket_arn" {
  description = "S3 bucket ARN"
  value       = aws_s3_bucket.backups.arn
}

# KMS
output "kms_key_arn" {
  description = "KMS key ARN (if enabled)"
  value       = var.enable_kms_encryption ? aws_kms_key.main[0].arn : null
}

# Helm values output (for helm install)
output "helm_values" {
  description = "Suggested values for Helm chart"
  value = <<-EOT
# values-aws.yaml
# Generated by Terraform

database:
  enabled: true
  external:
    enabled: true
    host: "${split(":", aws_db_instance.main.endpoint)[0]}"
    port: 5432
    database: "${var.db_name}"
    username: "${var.db_username}"
    existingSecret: "nis2-db-credentials"  # Create from Secrets Manager

backup:
  enabled: true
  # Configure s3 destination
  # bucket: ${aws_s3_bucket.backups.bucket}

replicator:
  enabled: true
  cloud:
    # Configure your cloud backup API
EOT
}
