# ============================================================================
# NIS2 Shield - Azure Terraform Outputs
# ============================================================================

output "location" {
  description = "Azure region"
  value       = var.location
}

# Resource Group
output "resource_group_name" {
  description = "Resource group name"
  value       = azurerm_resource_group.main.name
}

output "resource_group_id" {
  description = "Resource group ID"
  value       = azurerm_resource_group.main.id
}

# Virtual Network
output "vnet_id" {
  description = "Virtual network ID"
  value       = azurerm_virtual_network.main.id
}

output "vnet_name" {
  description = "Virtual network name"
  value       = azurerm_virtual_network.main.name
}

output "aks_subnet_id" {
  description = "AKS subnet ID"
  value       = azurerm_subnet.aks.id
}

output "database_subnet_id" {
  description = "Database subnet ID"
  value       = azurerm_subnet.db.id
}

# AKS
output "cluster_name" {
  description = "AKS cluster name"
  value       = azurerm_kubernetes_cluster.main.name
}

output "cluster_fqdn" {
  description = "AKS cluster FQDN"
  value       = azurerm_kubernetes_cluster.main.fqdn
}

output "cluster_id" {
  description = "AKS cluster ID"
  value       = azurerm_kubernetes_cluster.main.id
}

output "kube_config" {
  description = "Kubernetes config for kubectl"
  value       = azurerm_kubernetes_cluster.main.kube_config_raw
  sensitive   = true
}

output "cluster_identity" {
  description = "AKS managed identity principal ID"
  value       = azurerm_kubernetes_cluster.main.identity[0].principal_id
}

# PostgreSQL
output "database_fqdn" {
  description = "PostgreSQL server FQDN"
  value       = azurerm_postgresql_flexible_server.main.fqdn
}

output "database_id" {
  description = "PostgreSQL server ID"
  value       = azurerm_postgresql_flexible_server.main.id
}

output "database_name" {
  description = "Database name"
  value       = azurerm_postgresql_flexible_server_database.main.name
}

# Key Vault
output "key_vault_name" {
  description = "Key Vault name"
  value       = azurerm_key_vault.main.name
}

output "key_vault_uri" {
  description = "Key Vault URI"
  value       = azurerm_key_vault.main.vault_uri
}

output "key_vault_id" {
  description = "Key Vault ID"
  value       = azurerm_key_vault.main.id
}

# Storage
output "backup_storage_account" {
  description = "Backup storage account name"
  value       = azurerm_storage_account.backups.name
}

output "backup_storage_account_id" {
  description = "Backup storage account ID"
  value       = azurerm_storage_account.backups.id
}

output "backup_container" {
  description = "Backup container name"
  value       = azurerm_storage_container.backups.name
}

output "backup_primary_blob_endpoint" {
  description = "Primary blob endpoint for backups"
  value       = azurerm_storage_account.backups.primary_blob_endpoint
}

# Log Analytics
output "log_analytics_workspace_id" {
  description = "Log Analytics workspace ID"
  value       = azurerm_log_analytics_workspace.main.id
}

output "log_analytics_workspace_name" {
  description = "Log Analytics workspace name"
  value       = azurerm_log_analytics_workspace.main.name
}

# Helm values output (for helm install)
output "helm_values" {
  description = "Suggested values for Helm chart"
  value = <<-EOT
# values-azure.yaml
# Generated by Terraform

database:
  enabled: true
  external:
    enabled: true
    host: "${azurerm_postgresql_flexible_server.main.fqdn}"
    port: 5432
    database: "${var.db_name}"
    username: "${var.db_admin_login}"
    existingSecret: "nis2-db-credentials"  # Create from Key Vault

backup:
  enabled: true
  azure:
    storageAccount: "${azurerm_storage_account.backups.name}"
    container: "${azurerm_storage_container.backups.name}"

replicator:
  enabled: true
  cloud:
    # Configure your cloud backup API
EOT
}
